version: '3'
services:
  app:
    container_name: express_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    environment:
      PORT: 3000
      MONGO_DB_URI: ${MONGO_DB_URI}
      SPACE_NAME: ${SPACE_NAME}
      MAIL: ${MAIL}
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
